import crypto from "k6/crypto";
import http from "k6/http";
import { check, sleep } from "k6";

const BASE_URL = __ENV.BASE_URL || "http://localhost:8000";
const WEBHOOK_SECRET = __ENV.WEBHOOK_SECRET || "";
const RUN_ID = __ENV.K6_RUN_ID || `${Date.now()}`;

export const options = {
    scenarios: {
        webhook_smoke: {
            executor: "ramping-vus",
            stages: [
                { duration: "10s", target: 2 },
                { duration: "30s", target: 6 },
                { duration: "10s", target: 0 },
            ],
            gracefulRampDown: "5s",
        },
    },
    thresholds: {
        http_req_failed: ["rate<0.05"],
        http_req_duration: ["p(95)<1000", "p(99)<2000"],
        checks: ["rate>0.95"],
    },
    summaryTrendStats: ["avg", "min", "med", "p(90)", "p(95)", "p(99)", "max"],
};

function sign(body) {
    return crypto.hmac("sha256", WEBHOOK_SECRET, body, "hex");
}

function buildPayload() {
    const isCritical = __ITER % 10 === 0;
    return {
        alertname: isCritical ? "K6LearningCriticalLatency" : "K6LearningLatency",
        source: "k6",
        severity: isCritical ? "critical" : "warning",
        service: "webhookwise-api",
        instance: `vu-${__VU}`,
        run_id: RUN_ID,
        current_value: Math.round((80 + Math.random() * 50) * 100) / 100,
        threshold: 100,
        startsAt: new Date().toISOString(),
        annotations: {
            summary: "k6 learning stack synthetic webhook",
            description: "Generated by tests/k6/webhook_smoke.js",
        },
    };
}

export default function () {
    const body = JSON.stringify(buildPayload());
    const headers = {
        "Content-Type": "application/json",
        "X-Webhook-Source": "k6",
    };

    if (WEBHOOK_SECRET) {
        headers["X-Webhook-Signature"] = sign(body);
    }

    const response = http.post(`${BASE_URL}/v1/webhook/k6`, body, {
        headers,
        tags: {
            endpoint: "webhook_receive",
        },
    });

    check(response, {
        "webhook accepted": (r) => r.status === 200,
        "request id returned": (r) => (r.json("request_id") || "").length > 0,
    });

    sleep(0.5 + Math.random() * 1.5);
}
