"""Compatibility facade for the OpenClaw integration.

The implementation is split across focused modules:
- openclaw_client: HTTP/WebSocket protocol clients
- openclaw_poll: persisted polling state machine
- openclaw_analysis: analysis trigger and forwarding integration
"""

from __future__ import annotations

import websockets

from services.analysis.openclaw_analysis import (
    _build_openclaw_prompt_payload,
    _dict_or_empty,
    _extract_openclaw_overview,
    analyze_with_openclaw,
    forward_to_openclaw,
)
from services.analysis.openclaw_client import (
    OpenClawPollPolicy,
    OpenClawWsPolicy,
    _build_connect_frame,
    _build_device_auth,
    _describe_exception,
    _handshake,
    _http_to_ws_url,
    _loads_dict,
    _parse_history_messages,
    _try_recv_challenge,
    poll_openclaw_final,
    poll_session_result,
)
from services.analysis.openclaw_poll import (
    MANUAL_RETRY_STARTED_AT_KEY,
    _claim_openclaw_poll,
    _clamp_poll_delay_to_timeout,
    _clear_poll_stability,
    _completed_update,
    _elapsed_since,
    _failure_update_with_notification,
    _fetch_poll_result,
    _get_poll_stability,
    _handle_completed_poll_result,
    _handle_error_poll_result,
    _handle_missing_session_key,
    _handle_poll_result,
    _handle_poll_timeout,
    _is_same_poll_snapshot,
    _is_transient_poll_error,
    _poll_claim_lease_seconds,
    _poll_single_record,
    _poll_skip,
    _poll_snapshot,
    _poll_timeout_started_at,
    _poll_update,
    _record_to_poll_dict,
    _safe_notify,
    _schedule_next_openclaw_poll,
    _schedule_openclaw_poll_task,
    _seconds_until,
    _set_poll_stability,
    _text_hash,
    build_analysis_result_from_openclaw_text,
    clear_openclaw_poll_state,
    extract_robust_json,
    poll_deep_analysis_once,
    poll_openclaw_result_via_http,
    run_openclaw_poll_scan,
)

# Backwards-compatible escape hatch used by older tests and tools that monkeypatch
# the transport module through services.analysis.openclaw.websockets.
__all__ = [
    "MANUAL_RETRY_STARTED_AT_KEY",
    "OpenClawPollPolicy",
    "OpenClawWsPolicy",
    "_build_connect_frame",
    "_build_device_auth",
    "_build_openclaw_prompt_payload",
    "_claim_openclaw_poll",
    "_clear_poll_stability",
    "_clamp_poll_delay_to_timeout",
    "_completed_update",
    "_describe_exception",
    "_dict_or_empty",
    "_elapsed_since",
    "_extract_openclaw_overview",
    "_failure_update_with_notification",
    "_fetch_poll_result",
    "_get_poll_stability",
    "_handshake",
    "_handle_completed_poll_result",
    "_handle_error_poll_result",
    "_handle_missing_session_key",
    "_handle_poll_result",
    "_handle_poll_timeout",
    "_http_to_ws_url",
    "_is_same_poll_snapshot",
    "_is_transient_poll_error",
    "_loads_dict",
    "_parse_history_messages",
    "_poll_claim_lease_seconds",
    "_poll_single_record",
    "_poll_skip",
    "_poll_snapshot",
    "_poll_timeout_started_at",
    "_poll_update",
    "_record_to_poll_dict",
    "_safe_notify",
    "_schedule_next_openclaw_poll",
    "_schedule_openclaw_poll_task",
    "_seconds_until",
    "_set_poll_stability",
    "_text_hash",
    "_try_recv_challenge",
    "analyze_with_openclaw",
    "build_analysis_result_from_openclaw_text",
    "clear_openclaw_poll_state",
    "extract_robust_json",
    "forward_to_openclaw",
    "poll_deep_analysis_once",
    "poll_openclaw_final",
    "poll_openclaw_result_via_http",
    "poll_session_result",
    "run_openclaw_poll_scan",
    "websockets",
]
