apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: webhookwise
commonLabels:
  app.kubernetes.io/part-of: webhookwise
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - service-api.yaml
  - redis-service.yaml
  - redis-statefulset.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - deployment-api.yaml
  - deployment-worker.yaml
  - deployment-scheduler.yaml
  - job-migrate.yaml
images:
  - name: ghcr.io/itswl/webhookwise
    newTag: 0.1.0
