apiVersion: v1
kind: Service
metadata:
  name: webhookwise-postgres
  labels:
    app.kubernetes.io/name: webhookwise
    app.kubernetes.io/component: postgres
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    app.kubernetes.io/name: webhookwise
    app.kubernetes.io/component: postgres
