apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheus
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-5m"
        spanEndTimeShift: "5m"
        tags:
          - key: service.name
            value: service_name
          - key: deployment.environment
            value: deployment_environment
          - key: webhook.source
            value: webhook_source
          - key: webhook.status
            value: webhook_status
        filterByTraceID: true
        filterBySpanID: false
      tracesToProfiles:
        datasourceUid: pyroscope
        tags:
          - key: service.name
            value: service_name
          - key: deployment.environment
            value: deployment_environment
        profileTypeId: "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
      serviceMap:
        datasourceUid: prometheus
    uid: tempo
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '"trace_id":"([0-9a-f]{32})"'
          name: TraceID
          url: '$${__value.raw}'
          urlDisplayLabel: View Trace
  - name: Pyroscope
    type: grafana-pyroscope-datasource
    access: proxy
    url: http://pyroscope:4040
    uid: pyroscope
    jsonData:
      minStep: "15s"
